on:
  push:
    branches:
      - forestry

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '*'
    - run: node -v && npm -v
    - run: npm install
    - run: npm run production
    - uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        publish_dir: ./dist
        external_repository: Nullizer/nullizer.github.io
        publish_branch: master
