on:
  push:
    branches:
      - forestry

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '*'
    - run: node -v && npm -v
    - run: npm install
    - run: npm run production
